// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Copia struct {
	ID              int32        `json:"id"`
	JuegoID         int32        `json:"juego_id"`
	Plataforma      string       `json:"plataforma"`
	HorasJugadas    string       `json:"horas_jugadas"`
	LogrosObtenidos int32        `json:"logros_obtenidos"`
	CreatedAt       sql.NullTime `json:"created_at"`
}

type Juego struct {
	ID            int32        `json:"id"`
	Titulo        string       `json:"titulo"`
	Genero        string       `json:"genero"`
	LogrosTotales int32        `json:"logros_totales"`
	CreatedAt     sql.NullTime `json:"created_at"`
}
