// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const createCopia = `-- name: CreateCopia :one
INSERT INTO copias (juego_id, plataforma, horas_jugadas, logros_obtenidos)
VALUES ($1, $2, $3, $4)
RETURNING id, juego_id, plataforma, horas_jugadas, logros_obtenidos, created_at
`

type CreateCopiaParams struct {
	JuegoID         int32  `json:"juego_id"`
	Plataforma      string `json:"plataforma"`
	HorasJugadas    string `json:"horas_jugadas"`
	LogrosObtenidos int32  `json:"logros_obtenidos"`
}

func (q *Queries) CreateCopia(ctx context.Context, arg CreateCopiaParams) (Copia, error) {
	row := q.db.QueryRowContext(ctx, createCopia,
		arg.JuegoID,
		arg.Plataforma,
		arg.HorasJugadas,
		arg.LogrosObtenidos,
	)
	var i Copia
	err := row.Scan(
		&i.ID,
		&i.JuegoID,
		&i.Plataforma,
		&i.HorasJugadas,
		&i.LogrosObtenidos,
		&i.CreatedAt,
	)
	return i, err
}

const createJuego = `-- name: CreateJuego :one
INSERT INTO juegos (titulo, genero, logros_totales)
VALUES ($1, $2, $3)
RETURNING id, titulo, genero, logros_totales, created_at
`

type CreateJuegoParams struct {
	Titulo        string `json:"titulo"`
	Genero        string `json:"genero"`
	LogrosTotales int32  `json:"logros_totales"`
}

func (q *Queries) CreateJuego(ctx context.Context, arg CreateJuegoParams) (Juego, error) {
	row := q.db.QueryRowContext(ctx, createJuego, arg.Titulo, arg.Genero, arg.LogrosTotales)
	var i Juego
	err := row.Scan(
		&i.ID,
		&i.Titulo,
		&i.Genero,
		&i.LogrosTotales,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCopia = `-- name: DeleteCopia :exec
DELETE FROM copias
WHERE id = $1
`

func (q *Queries) DeleteCopia(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteCopia, id)
	return err
}

const deleteJuego = `-- name: DeleteJuego :exec
DELETE FROM juegos
WHERE id = $1
`

func (q *Queries) DeleteJuego(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteJuego, id)
	return err
}

const getJuegoByID = `-- name: GetJuegoByID :one
SELECT id, titulo, genero, logros_totales, created_at FROM juegos
WHERE id = $1
`

func (q *Queries) GetJuegoByID(ctx context.Context, id int32) (Juego, error) {
	row := q.db.QueryRowContext(ctx, getJuegoByID, id)
	var i Juego
	err := row.Scan(
		&i.ID,
		&i.Titulo,
		&i.Genero,
		&i.LogrosTotales,
		&i.CreatedAt,
	)
	return i, err
}

const getJuegoByTitulo = `-- name: GetJuegoByTitulo :one
SELECT id, titulo, genero, logros_totales, created_at FROM juegos
WHERE titulo = $1
`

func (q *Queries) GetJuegoByTitulo(ctx context.Context, titulo string) (Juego, error) {
	row := q.db.QueryRowContext(ctx, getJuegoByTitulo, titulo)
	var i Juego
	err := row.Scan(
		&i.ID,
		&i.Titulo,
		&i.Genero,
		&i.LogrosTotales,
		&i.CreatedAt,
	)
	return i, err
}

const listCopiasByJuego = `-- name: ListCopiasByJuego :many
SELECT id, juego_id, plataforma, horas_jugadas, logros_obtenidos, created_at FROM copias
WHERE juego_id = $1
ORDER BY plataforma ASC
`

func (q *Queries) ListCopiasByJuego(ctx context.Context, juegoID int32) ([]Copia, error) {
	rows, err := q.db.QueryContext(ctx, listCopiasByJuego, juegoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Copia
	for rows.Next() {
		var i Copia
		if err := rows.Scan(
			&i.ID,
			&i.JuegoID,
			&i.Plataforma,
			&i.HorasJugadas,
			&i.LogrosObtenidos,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJuegos = `-- name: ListJuegos :many
SELECT id, titulo, genero, logros_totales, created_at FROM juegos
ORDER BY titulo ASC
`

func (q *Queries) ListJuegos(ctx context.Context) ([]Juego, error) {
	rows, err := q.db.QueryContext(ctx, listJuegos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Juego
	for rows.Next() {
		var i Juego
		if err := rows.Scan(
			&i.ID,
			&i.Titulo,
			&i.Genero,
			&i.LogrosTotales,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJuego = `-- name: UpdateJuego :exec
UPDATE juegos
SET titulo = $2, genero = $3, logros_totales = $4
WHERE id = $1
`

type UpdateJuegoParams struct {
	ID            int32  `json:"id"`
	Titulo        string `json:"titulo"`
	Genero        string `json:"genero"`
	LogrosTotales int32  `json:"logros_totales"`
}

func (q *Queries) UpdateJuego(ctx context.Context, arg UpdateJuegoParams) error {
	_, err := q.db.ExecContext(ctx, updateJuego,
		arg.ID,
		arg.Titulo,
		arg.Genero,
		arg.LogrosTotales,
	)
	return err
}
